"""
Configuration File.
Author : Abir Mukherjee (codinion/mabir)
Email : abir.mukherjee0595@gmail.com
"""

#Stage Configurations
SCORE_W=512
SCORE_H=18
STAGE_W=512
STAGE_H=512
DELTA_H=16
DELTA_W=24
STAGE_MARGIN_X=8
STAGE_MARGIN_Y=8
SCREEN_W=STAGE_W+DELTA_W
SCREEN_H=SCORE_H+STAGE_H+DELTA_H
FONT_SIZE=14
LAST_SCORE_FONT_SIZE=24
STAGE_X=5
STAGE_Y=SCORE_H
SCORE_X=1
SCORE_Y=1

#EndScreen Configuration
GAMEOVER_X=120
GAMEOVER_Y=240
GAMEWON_X=90
GAMEWON_Y=240
LAST_SCORE_X=180
LAST_SCORE_Y=320
HIGH_SCORE_X=180
HIGH_SCORE_Y=320
GAMEOVER_FONT_SIZE=56
GAMEWON_FONT_SIZE=56
HIGH_SCORE_FONT_SIZE=24
INST_RST_X=200
INST_RST_Y=400
INST_QT_X=200
INST_QT_Y=420

#Game Rules Configuration
WINNING_SCORE=25
INIT_SLEEP=0.14
MIN_SLEEP=0.04
LEVEL_UP=3
LEVEL_DT=0.02
BOUNDS=True

#Sprite Configurations
IMAGE_W=128
IMAGE_H=128
SPRITE_W=16
SPRITE_H=16
BODY_W=128
BODY_H=128
HEAD_H=128
HEAD_W=128
FOOD_W=128
FOOD_H=128
LAND_W=128
LAND_H=128

#Asset Configurations
HEAD_FILE='assets/head.png'
BODY_FILE='assets/body.png'
FOOD_FILE='assets/food.png'
LAND_FILE='assets/land_box.png'
FONT_FILE='assets/OpenSansBold.ttf'
MUSIC_FILE='assets/background.ogg'
COLLIDE_SFX_FILE='assets/collide.ogg'
EAT_SFX_FILE='assets/eat.ogg'
WIN_SFX_FILE='assets/cheer.ogg'

#Snake Configuration
INIT_SNAKE_W=5
INIT_SNAKE_D='R'
INIT_HEAD_X=(STAGE_W/SPRITE_W)//2
INIT_HEAD_Y=(STAGE_H/SPRITE_H)//2
